import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/Header/Header";
import Footer from "./components/Footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body className='bg-soft-light h-screen '>
        <div className='flex flex-col h-screen m-auto'>
            <Header></Header>
            <main className='flex-1'>
                {children}
            </main>
            <Footer></Footer>
        </div>
      </body>
    </html>
  );
}
